# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCW-Wg3m7LqI1rq5rszHafgqlpcNOYD4
"""

import pandas as pd

df = pd.read_csv("/content/WA_Fn-UseC_-HR-Employee-Attrition.csv")

# Drop constant / non-informative columns
df = df.drop(columns=["EmployeeCount", "StandardHours", "Over18", "EmployeeNumber"])

# Encode target and binary column
df["Attrition"] = (df["Attrition"] == "Yes").astype(int)
df["OverTime"]  = (df["OverTime"] == "Yes").astype(int)

print(df.shape)
df.head()

import matplotlib.pyplot as plt

df["Attrition"].value_counts(normalize=True).plot(kind="bar", title="Attrition rate")
plt.ylabel("Proportion")
plt.show()

print("Average monthly income by attrition:")
print(df.groupby("Attrition")["MonthlyIncome"].mean())

print("\nOvertime rate by attrition:")
print(df.groupby("Attrition")["OverTime"].mean())

print("\nAttrition rate by job role (highest risk first):")
print(df.groupby("JobRole")["Attrition"].mean().sort_values(ascending=False))

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

features = ["Age","YearsAtCompany","JobSatisfaction","DistanceFromHome",
            "OverTime","TotalWorkingYears","WorkLifeBalance","JobLevel"]

X = df[features]
y = df["Attrition"]

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler().fit(Xtr)
Xtr_s, Xte_s = scaler.transform(Xtr), scaler.transform(Xte)

logit = LogisticRegression(max_iter=1000, class_weight="balanced").fit(Xtr_s, ytr)

pred = logit.predict(Xte_s)
print("Accuracy:", accuracy_score(yte, pred))
print(classification_report(yte, pred))
print("Confusion matrix:\n", confusion_matrix(yte, pred))

coef_table = pd.Series(logit.coef_[0], index=features).sort_values()
print(coef_table)

coef_table.plot(kind="barh", title="Logistic regression coefficients (standardized)")
plt.axvline(0, color="black", linewidth=0.8)
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

lin_feats = ["Age","TotalWorkingYears","JobLevel","YearsAtCompany"]
Xl = df[lin_feats]
yl = df["MonthlyIncome"]

Xltr, Xlte, yltr, ylte = train_test_split(Xl, yl, test_size=0.2, random_state=42)

lin = LinearRegression().fit(Xltr, yltr)
pred_l = lin.predict(Xlte)

print("R²:", r2_score(ylte, pred_l))
print("MAE:", mean_absolute_error(ylte, pred_l))
print("\nCoefficients:")
print(pd.Series(lin.coef_, index=lin_feats))

import joblib

joblib.dump(logit, "logit.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(lin, "lin.pkl")

print("Saved: logit.pkl, scaler.pkl, lin.pkl")

